import { User, Subject, Exam, Question, Assignment, Material, ExamAttempt } from '../types';

const nowIso = new Date().toISOString();
const pastDate = (daysAgo: number) => new Date(Date.now() - daysAgo * 86400000).toISOString();

export const MOCK_USERS: User[] = [
  {
    id: 'user-admin-1',
    email: 'admin@test.com',
    fullName: 'TS. Nguyễn Văn Quản Trị',
    role: 'ADMIN',
    tier: 'PRO',
    status: 'ACTIVE',
    phoneNumber: '0901234567',
    createdAt: pastDate(30),
    updatedAt: nowIso,
  },
  {
    id: 'user-student-1',
    email: 'student@test.com',
    fullName: 'Nguyễn Văn An (Học sinh PRO)',
    role: 'STUDENT',
    tier: 'PRO',
    status: 'ACTIVE',
    phoneNumber: '0987654321',
    proExpiresAt: new Date(Date.now() + 365 * 86400000).toISOString(),
    createdAt: pastDate(15),
    updatedAt: nowIso,
  },
  {
    id: 'user-student-2',
    email: 'free@test.com',
    fullName: 'Trần Thị Bình (Học sinh Free)',
    role: 'STUDENT',
    tier: 'FREE',
    status: 'ACTIVE',
    phoneNumber: '0912345678',
    createdAt: pastDate(10),
    updatedAt: nowIso,
  },
  {
    id: 'user-student-3',
    email: 'le.hoang@test.com',
    fullName: 'Lê Hoàng Minh',
    role: 'STUDENT',
    tier: 'FREE',
    status: 'ACTIVE',
    phoneNumber: '0933445566',
    createdAt: pastDate(5),
    updatedAt: nowIso,
  },
];

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: 'subj-math',
    name: 'Toán Học',
    code: 'MATH',
    description: 'Chương trình Toán 12 & Ôn thi Tốt nghiệp THPT Quốc gia',
    order: 1,
    isActive: true,
    createdAt: pastDate(40),
    updatedAt: nowIso,
  },
  {
    id: 'subj-phys',
    name: 'Vật Lý',
    code: 'PHYS',
    description: 'Vật lý 12, Cơ học, Sóng cơ và Dòng điện xoay chiều',
    order: 2,
    isActive: true,
    createdAt: pastDate(40),
    updatedAt: nowIso,
  },
  {
    id: 'subj-chem',
    name: 'Hóa Học',
    code: 'CHEM',
    description: 'Hóa học Hữu cơ & Vô cơ chuyên sâu',
    order: 3,
    isActive: true,
    createdAt: pastDate(40),
    updatedAt: nowIso,
  },
  {
    id: 'subj-eng',
    name: 'Tiếng Anh',
    code: 'ENG',
    description: 'Ngữ pháp, Đọc hiểu và Luyện đề trắc nghiệm chuẩn Quốc gia',
    order: 4,
    isActive: true,
    createdAt: pastDate(40),
    updatedAt: nowIso,
  },
];

export const MOCK_QUESTIONS_EXAM_1: Question[] = [
  {
    id: 'q-1',
    examId: 'exam-1',
    subjectId: 'subj-math',
    content: 'Cho hàm số y = f(x) có đạo hàm f\'(x) = (x - 1)(x + 2)^2 (x - 3). Số điểm cực trị của hàm số đã cho là:',
    type: 'SINGLE_CHOICE',
    points: 1,
    timeLimit: 60,
    order: 0,
    instruction: 'Chọn 1 phương án trả lời đúng nhất',
    hint: 'Điểm cực trị chỉ xuất hiện tại các nghiệm bội lẻ của phương trình f\'(x) = 0.',
    explanation: 'f\'(x) = 0 <=> x = 1 (bội 1), x = -2 (bội 2), x = 3 (bội 1). Đạo hàm chỉ đổi dấu khi đi qua các nghiệm bội lẻ là x = 1 và x = 3. Vậy hàm số có đúng 2 điểm cực trị.',
    options: [
      { id: 'opt-1-a', label: 'A', content: '1', isCorrect: false },
      { id: 'opt-1-b', label: 'B', content: '2', isCorrect: true },
      { id: 'opt-1-c', label: 'C', content: '3', isCorrect: false },
      { id: 'opt-1-d', label: 'D', content: '4', isCorrect: false },
    ],
  },
  {
    id: 'q-2',
    examId: 'exam-1',
    subjectId: 'subj-math',
    content: 'Tập nghiệm của bất phương trình log_2(x - 1) < 3 là:',
    type: 'SINGLE_CHOICE',
    points: 1,
    timeLimit: 45,
    order: 1,
    hint: 'Đừng quên điều kiện xác định của biểu thức dưới dấu logarit (x - 1 > 0).',
    explanation: 'Điều kiện: x - 1 > 0 <=> x > 1. BPT tương đương: x - 1 < 2^3 = 8 <=> x < 9. Kết hợp điều kiện ta được: 1 < x < 9 hay tập nghiệm là (1; 9).',
    options: [
      { id: 'opt-2-a', label: 'A', content: '(1; 9)', isCorrect: true },
      { id: 'opt-2-b', label: 'B', content: '(-∞; 9)', isCorrect: false },
      { id: 'opt-2-c', label: 'C', content: '(1; 8)', isCorrect: false },
      { id: 'opt-2-d', label: 'D', content: '[1; 9)', isCorrect: false },
    ],
  },
  {
    id: 'q-3',
    examId: 'exam-1',
    subjectId: 'subj-math',
    content: 'Trong không gian Oxyz, cho mặt phẳng (P): 2x - y + 3z - 5 = 0. Vectơ nào sau đây là một vectơ pháp tuyến của (P)?',
    type: 'SINGLE_CHOICE',
    points: 1,
    timeLimit: 30,
    order: 2,
    explanation: 'Vectơ pháp tuyến của mặt phẳng Ax + By + Cz + D = 0 có dạng n = (A, B, C). Với (P): 2x - y + 3z - 5 = 0 thì n = (2, -1, 3).',
    options: [
      { id: 'opt-3-a', label: 'A', content: 'n = (2; 1; 3)', isCorrect: false },
      { id: 'opt-3-b', label: 'B', content: 'n = (2; -1; 3)', isCorrect: true },
      { id: 'opt-3-c', label: 'C', content: 'n = (2; -1; -5)', isCorrect: false },
      { id: 'opt-3-d', label: 'D', content: 'n = (-2; 1; 3)', isCorrect: false },
    ],
  },
  {
    id: 'q-4',
    examId: 'exam-1',
    subjectId: 'subj-math',
    content: 'Thể tích của khối chóp có diện tích đáy B = 6 cm² và chiều cao h = 5 cm bằng bao nhiêu cm³?',
    type: 'SINGLE_CHOICE',
    points: 1,
    timeLimit: 30,
    order: 3,
    explanation: 'Công thức thể tích khối chóp là V = (1/3) * B * h = (1/3) * 6 * 5 = 10 cm³.',
    options: [
      { id: 'opt-4-a', label: 'A', content: '30 cm³', isCorrect: false },
      { id: 'opt-4-b', label: 'B', content: '15 cm³', isCorrect: false },
      { id: 'opt-4-c', label: 'C', content: '10 cm³', isCorrect: true },
      { id: 'opt-4-d', label: 'D', content: '20 cm³', isCorrect: false },
    ],
  },
  {
    id: 'q-5',
    examId: 'exam-1',
    subjectId: 'subj-math',
    content: 'Có bao nhiêu giá trị nguyên của m để hàm số y = (x + 2)/(x + 3m) đồng biến trên khoảng (-∞; -6)?',
    type: 'SINGLE_CHOICE',
    points: 2,
    timeLimit: 90,
    order: 4,
    hint: 'Tính y\', yêu cầu y\' > 0 và điểm gián đoạn -3m không thuộc khoảng (-∞; -6).',
    explanation: 'y\' = (3m - 2)/(x + 3m)^2. Hàm số đồng biến <=> 3m - 2 > 0 (m > 2/3) và -3m >= -6 (m <= 2). Vậy 2/3 < m <= 2 => m ∈ {1, 2}. Có 2 giá trị nguyên.',
    options: [
      { id: 'opt-5-a', label: 'A', content: '1', isCorrect: false },
      { id: 'opt-5-b', label: 'B', content: '2', isCorrect: true },
      { id: 'opt-5-c', label: 'C', content: '3', isCorrect: false },
      { id: 'opt-5-d', label: 'D', content: 'Vô số', isCorrect: false },
    ],
  },
];

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'exam-1',
    title: 'Đề Thi Thử THPT Quốc Gia 2026 - Môn Toán (Mã đề 101)',
    description: 'Bộ đề thi chuẩn cấu trúc Bộ GD&ĐT gồm các chuyên đề Hàm số, Mũ - Logarit và Hình học Oxyz.',
    subjectId: 'subj-math',
    subject: MOCK_SUBJECTS[0],
    durationMinutes: 45,
    passingScore: 5.0,
    totalPoints: 10,
    status: 'PUBLISHED',
    accessLevel: 'FREE',
    questionsCount: 5,
    createdAt: pastDate(7),
    updatedAt: pastDate(1),
  },
  {
    id: 'exam-2',
    title: 'Khảo Sát Chất Lượng Vật Lý - Chuyên Đề Sóng Cơ & Dao Động',
    description: 'Kiểm tra 45 phút các kiến thức cốt lõi về Sóng âm, Giao thoa sóng và Sóng dừng.',
    subjectId: 'subj-phys',
    subject: MOCK_SUBJECTS[1],
    durationMinutes: 45,
    passingScore: 5.0,
    totalPoints: 10,
    status: 'PUBLISHED',
    accessLevel: 'FREE',
    questionsCount: 4,
    createdAt: pastDate(5),
    updatedAt: pastDate(2),
  },
  {
    id: 'exam-3',
    title: 'Chuyên Đề PRO: Bứt Phá Điểm 9+ Môn Toán - Hình Học Không Gian',
    description: 'Tuyển tập 50 câu hỏi vận dụng cao hình học không gian và phương pháp tọa độ hóa Oxyz.',
    subjectId: 'subj-math',
    subject: MOCK_SUBJECTS[0],
    durationMinutes: 60,
    passingScore: 7.0,
    totalPoints: 10,
    status: 'PUBLISHED',
    accessLevel: 'PRO',
    questionsCount: 10,
    createdAt: pastDate(3),
    updatedAt: pastDate(1),
  },
  {
    id: 'exam-4',
    title: 'Đề Thi Thử Tiếng Anh THPT - Mã Đề 402 (Bản Nháp)',
    description: 'Đề kiểm tra kỹ năng đọc hiểu và tìm lỗi sai ngữ pháp.',
    subjectId: 'subj-eng',
    subject: MOCK_SUBJECTS[3],
    durationMinutes: 60,
    passingScore: 5.0,
    totalPoints: 10,
    status: 'DRAFT',
    accessLevel: 'FREE',
    questionsCount: 2,
    createdAt: pastDate(1),
    updatedAt: nowIso,
  },
];

export const MOCK_ASSIGNMENTS: Assignment[] = [
  {
    id: 'assign-1',
    examId: 'exam-1',
    studentId: 'user-student-1',
    exam: MOCK_EXAMS[0],
    student: MOCK_USERS[1],
    status: 'PENDING',
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    createdAt: pastDate(2),
    updatedAt: nowIso,
  },
  {
    id: 'assign-2',
    examId: 'exam-2',
    studentId: 'user-student-1',
    exam: MOCK_EXAMS[1],
    student: MOCK_USERS[1],
    status: 'COMPLETED',
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    createdAt: pastDate(4),
    updatedAt: nowIso,
    examAttempts: [
      {
        id: 'attempt-sample-1',
        status: 'COMPLETED',
        score: 8.5,
      },
    ],
  },
  {
    id: 'assign-3',
    examId: 'exam-3',
    studentId: 'user-student-1',
    exam: MOCK_EXAMS[2],
    student: MOCK_USERS[1],
    status: 'PENDING',
    dueDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    createdAt: pastDate(1),
    updatedAt: nowIso,
  },
];

export const MOCK_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    title: 'Sổ Tay Công Thức Toán 12 Toàn Diện & Giải Nhanh',
    materialType: 'PDF',
    storageUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    accessLevel: 'FREE',
    subjectId: 'subj-math',
    subject: MOCK_SUBJECTS[0],
    isPublished: true,
    createdAt: pastDate(10),
    updatedAt: nowIso,
  },
  {
    id: 'mat-2',
    title: 'Video Bài Giảng: Kỹ Thuật Đọc Đồ Thị Sóng Dừng Trong 3 Phút',
    materialType: 'EMBEDDED_VIDEO',
    embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    accessLevel: 'FREE',
    subjectId: 'subj-phys',
    subject: MOCK_SUBJECTS[1],
    isPublished: true,
    createdAt: pastDate(8),
    updatedAt: nowIso,
  },
  {
    id: 'mat-3',
    title: 'Tài Liệu PRO: Tuyển Tập 100 Câu Vận Dụng Cao Hóa Hữu Cơ',
    materialType: 'PDF',
    storageUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    accessLevel: 'PRO',
    subjectId: 'subj-chem',
    subject: MOCK_SUBJECTS[2],
    isPublished: true,
    createdAt: pastDate(5),
    updatedAt: nowIso,
  },
];

export const MOCK_ATTEMPTS: ExamAttempt[] = [
  {
    id: 'attempt-sample-1',
    examId: 'exam-1',
    studentId: 'user-student-1',
    assignmentId: 'assign-1',
    score: 8.0,
    status: 'COMPLETED',
    startedAt: pastDate(1),
    submittedAt: new Date(Date.now() - 86400000 + 20 * 60000).toISOString(),
    durationSeconds: 1200,
    totalQuestions: 5,
    correctAnswers: 4,
    exam: MOCK_EXAMS[0],
    student: MOCK_USERS[1],
    questions: MOCK_QUESTIONS_EXAM_1,
    answers: [
      { questionId: 'q-1', selectedOptionId: 'opt-1-b', isCorrect: true, score: 1 },
      { questionId: 'q-2', selectedOptionId: 'opt-2-a', isCorrect: true, score: 1 },
      { questionId: 'q-3', selectedOptionId: 'opt-3-b', isCorrect: true, score: 1 },
      { questionId: 'q-4', selectedOptionId: 'opt-4-c', isCorrect: true, score: 1 },
      { questionId: 'q-5', selectedOptionId: 'opt-5-a', isCorrect: false, score: 0 },
    ],
  },
];
